version: "2"
services:
  db:
    image: mongodb
    restart: always
    ports:
      - 172.17.0.1:27017:27017
    volumes:
      - /home/laekov/db:/data/db
  web:
    image: tuoj-web
    restart: always
    ports:
      - 127.0.0.1:8004:3333
    volumes:
      - /home/laekov/tuoj/tuoj-web/oj:/srv/tuoj-web
    command:
      bash /srv/tuoj-web/tools/run.sh
networks:
  default:
    external:
      name: service-network
